import type { ProgramLibraryCategory, ProgramModule, ProgramSection, ProgramTool } from "./types";

export const PROGRAM_SECTIONS: ProgramSection[] = ["Calm", "Energy", "Planning", "Rest", "Reflection"];

export const PROGRAM_LIBRARY_CATEGORIES: ProgramLibraryCategory[] = [
  "grounding",
  "overwhelm",
  "low-energy",
  "sleep",
  "pacing",
  "brain-fog",
  "emotional-regulation",
  "care-prep",
];

const CORE_PROGRAM_MODULES: ProgramModule[] = [
  {
    id: "reduce-overwhelm-support",
    title: "Reduce overwhelm",
    section: "Calm",
    category: "overwhelm",
    track: "stress-support",
    description: "Lower the amount the next few minutes are asking from you.",
    whyItHelps: "Reducing input and decisions can make the next step easier to find.",
    estimatedPace: "1-2 minutes",
    toolIds: ["reduce-overwhelm"],
    content: [],
  },
  {
    id: "brain-fog-basics",
    title: "Brain fog support",
    section: "Planning",
    category: "brain-fog",
    track: "cognitive-support",
    description: "Narrow the next steps when thinking feels slower or crowded.",
    whyItHelps: "Keeping fewer steps visible can reduce mental load during brain fog.",
    estimatedPace: "2 minutes",
    toolIds: ["brain-fog-basics"],
    content: [],
  },
  {
    id: "appointment-prep-support",
    title: "Appointment prep",
    section: "Planning",
    category: "care-prep",
    track: "cognitive-support",
    description: "Prepare a short list of topics for a care visit.",
    whyItHelps: "A brief outline can make appointments easier to navigate when energy is limited.",
    estimatedPace: "3 minutes",
    toolIds: ["appointment-prep"],
    content: [],
  },
  {
    id: "nervous-system-reset",
    title: "Nervous system reset",
    section: "Calm",
    category: "grounding",
    track: "nervous-system",
    description: "Short grounding tools for moments when your system feels overloaded.",
    whyItHelps: "A brief pause can help the day feel less sharp and more manageable.",
    estimatedPace: "1-2 minutes",
    toolIds: ["breathing-reset", "body-scan"],
    content: [
      {
        id: "nsr-note-1",
        kind: "wellness-note",
        title: "When to use this",
        body: "This module can help when stress is high, your body feels tense, or you need a softer reset before choosing your next step.",
      },
    ],
  },
  {
    id: "energy-support",
    title: "Energy support",
    section: "Energy",
    category: "low-energy",
    track: "energy-management",
    description: "Low-energy guidance for days when doing less may help more.",
    whyItHelps: "Protecting energy early can make the rest of the day feel steadier.",
    estimatedPace: "2 minutes",
    toolIds: ["low-energy-checklist"],
    content: [
      {
        id: "energy-guide-1",
        kind: "micro-guide",
        title: "One gentle principle",
        body: "Try choosing one main task, one support action, and one thing that can wait. That can be enough.",
      },
    ],
  },
  {
    id: "gentle-planning",
    title: "Gentle planning",
    section: "Planning",
    category: "pacing",
    track: "mindfulness",
    description: "Small planning tools for lowering decision load without adding pressure.",
    whyItHelps: "A clearer next step can reduce the feeling that everything is urgent at once.",
    estimatedPace: "2 minutes",
    toolIds: ["one-priority-planner"],
    content: [
      {
        id: "planning-prompt-1",
        kind: "reflection-prompt",
        title: "A useful question",
        body: "What matters most today, and what would make it a little easier to begin?",
      },
    ],
  },
  {
    id: "heavier-day-reflection",
    title: "Heavier day reflection",
    section: "Reflection",
    category: "emotional-regulation",
    track: "emotional-resilience",
    description: "Short reflection support for difficult moments and heavier weeks.",
    whyItHelps: "Naming what feels hard can make it easier to meet the moment with a little more steadiness.",
    estimatedPace: "3 minutes",
    toolIds: ["hard-moment-reflection"],
    content: [
      {
        id: "reflection-guide-1",
        kind: "micro-guide",
        title: "Keep it small",
        body: "You do not need a full journal entry. One honest sentence is often enough to help you come back to the day more gently.",
      },
    ],
  },
];

const PREMIUM_PROGRAM_MODULES: ProgramModule[] = [
  {
    id: "symptom-reflection-support",
    title: "Symptom reflection",
    section: "Reflection",
    category: "brain-fog",
    track: "cognitive-support",
    premiumFeature: "guided_programs",
    description: "Notice symptom changes, possible triggers, and what may help.",
    whyItHelps: "A short structured note can make symptom patterns easier to recognize and discuss later.",
    estimatedPace: "3 minutes",
    toolIds: ["symptom-reflection"],
    content: [],
  },
  {
    id: "overwhelm-support",
    title: "Overwhelm support",
    section: "Calm",
    category: "overwhelm",
    track: "stress-support",
    premiumFeature: "guided_programs",
    description: "Short support for mentally overloaded moments when everything feels too loud at once.",
    whyItHelps: "A smaller support surface can help the day feel less sharp without asking much from you.",
    estimatedPace: "2-3 minutes",
    toolIds: ["sixty-second-quiet-reset", "mentally-overloaded-reset", "two-minute-overwhelm-reset"],
    content: [
      {
        id: "overwhelm-note-1",
        kind: "wellness-note",
        title: "A gentler frame",
        body: "You do not need to figure out the whole day while you are overwhelmed. A smaller moment of steadiness can be enough first.",
      },
    ],
  },
  {
    id: "sensory-reset",
    title: "Calming sensory reset",
    section: "Calm",
    category: "grounding",
    track: "nervous-system",
    premiumFeature: "guided_programs",
    description: "A quieter reset for moments when your environment or body feels overstimulating.",
    whyItHelps: "Lowering sensory input can make the rest of the day feel more workable.",
    estimatedPace: "2 minutes",
    toolIds: ["calming-sensory-reset", "reduce-stimulation-guide"],
    content: [
      {
        id: "sensory-audio-1",
        kind: "audio-cue",
        title: "Optional sound support",
        body: "If a steady sound helps, choose one low, familiar sound you already trust. Silence is also fine.",
      },
    ],
  },
  {
    id: "emotional-reset-rituals",
    title: "Emotional reset rituals",
    section: "Calm",
    category: "overwhelm",
    track: "stress-support",
    premiumFeature: "guided_programs",
    description: "Short reset rituals for stressful moments that leave emotional or nervous-system carryover behind.",
    whyItHelps: "A quieter transition can help the next part of the day feel less sharp without turning recovery into a whole process.",
    estimatedPace: "1-3 minutes",
    toolIds: [
      "sixty-second-quiet-reset",
      "slow-things-down-reset",
      "nervous-system-downshift",
      "reduce-emotional-carryover",
    ],
    content: [
      {
        id: "reset-note-1",
        kind: "wellness-note",
        title: "Keep the reset small",
        body: "Nothing here needs to become a ritual to perform. A shorter transition can still help the next hour feel more manageable.",
      },
    ],
  },
  {
    id: "low-energy-recovery",
    title: "Low-energy recovery",
    section: "Energy",
    category: "low-energy",
    track: "energy-management",
    premiumFeature: "guided_programs",
    description: "A few steadier options for mornings, evenings, or heavier stretches when energy stays low.",
    whyItHelps: "A smaller rhythm can protect energy before the day asks too much.",
    estimatedPace: "2-4 minutes",
    toolIds: ["difficult-morning-support", "low-energy-evening-wind-down"],
    content: [
      {
        id: "low-energy-note-1",
        kind: "micro-guide",
        title: "Keep the bar low",
        body: "If energy is low, reducing friction may help more than trying to feel fully caught up.",
      },
    ],
  },
  {
    id: "difficult-day-support",
    title: "Difficult-day support",
    section: "Energy",
    category: "low-energy",
    track: "energy-management",
    premiumFeature: "guided_programs",
    description: "Ultra-low-demand support for days when everything feels harder, heavier, or more effortful.",
    whyItHelps: "Reducing pressure early can help the day feel a little more survivable without asking much from you.",
    estimatedPace: "1-3 minutes",
    toolIds: ["everything-feels-too-hard", "i-cant-do-much-today", "less-pressure-reset"],
    content: [
      {
        id: "difficult-day-note-1",
        kind: "wellness-note",
        title: "Keep the bar low",
        body: "This is for the days when functioning feels harder. One softer choice may be enough.",
      },
    ],
  },
  {
    id: "brain-fog-support",
    title: "Brain fog support",
    section: "Planning",
    category: "brain-fog",
    track: "cognitive-support",
    premiumFeature: "guided_programs",
    description: "Short support for mentally cloudy moments when holding onto steps feels harder.",
    whyItHelps: "A smaller cognitive load can make it easier to move through the next hour without pressure.",
    estimatedPace: "2 minutes",
    toolIds: ["brain-fog-clarifier", "decision-light-reset", "cognitive-decompression-reset", "too-many-thoughts-at-once"],
    content: [
      {
        id: "brain-fog-note-1",
        kind: "wellness-note",
        title: "What this is for",
        body: "This is not about pushing through. It is for reducing decisions when thinking already feels expensive.",
      },
    ],
  },
  {
    id: "mental-exhaustion-recovery",
    title: "Mental exhaustion recovery",
    section: "Energy",
    category: "brain-fog",
    track: "cognitive-support",
    premiumFeature: "guided_programs",
    description: "Lower-demand recovery support for cognitively drained, depleted, or mentally emptied-out periods.",
    whyItHelps: "A quieter recovery surface can help after mentally exhausting stretches without turning recovery into another demand.",
    estimatedPace: "2-4 minutes",
    toolIds: ["empty-tank-support", "mental-rest-permission", "cognitive-decompression-reset", "slower-recovery-pacing"],
    content: [
      {
        id: "mental-exhaustion-note-1",
        kind: "wellness-note",
        title: "Keep recovery small",
        body: "This is for the moments when your brain feels spent. A lower-demand next step can still count as recovery.",
      },
    ],
  },
  {
    id: "cognitive-simplification",
    title: "Cognitive simplification",
    section: "Planning",
    category: "brain-fog",
    track: "cognitive-support",
    premiumFeature: "guided_programs",
    description: "Small practical tools for mentally noisy hours, decision fatigue, and memory friction.",
    whyItHelps: "Reducing choices and keeping one thing visible can make the next stretch feel more workable.",
    estimatedPace: "1-3 minutes",
    toolIds: ["one-thing-at-a-time", "simplify-the-next-hour", "reduce-mental-load"],
    content: [
      {
        id: "cognitive-simplification-note-1",
        kind: "micro-guide",
        title: "Keep the field narrow",
        body: "This is for making the next stretch easier to hold onto, not for becoming more productive.",
      },
    ],
  },
  {
    id: "pacing-after-overwhelm",
    title: "Pacing after overwhelming days",
    section: "Planning",
    category: "pacing",
    track: "mindfulness",
    premiumFeature: "guided_programs",
    description: "Gentle pacing support after heavier days so recovery does not become another task.",
    whyItHelps: "A slower next step can help you come back without pushing too hard too soon.",
    estimatedPace: "3 minutes",
    toolIds: ["difficult-day-pacing-checklist", "pacing-after-overwhelm"],
    content: [
      {
        id: "pacing-note-1",
        kind: "micro-guide",
        title: "After a heavier day",
        body: "A steadier return often starts with asking less from the next block of time, not more.",
      },
    ],
  },
  {
    id: "life-transition-support",
    title: "Travel and disrupted-routine support",
    section: "Planning",
    category: "pacing",
    track: "mindfulness",
    premiumFeature: "guided_programs",
    description: "Calmer support for travel, routine changes, and weeks that stop feeling predictable.",
    whyItHelps: "A gentler re-entry can help after disruptions without turning continuity into pressure.",
    estimatedPace: "2-4 minutes",
    toolIds: [
      "travel-day-pacing",
      "disrupted-routine-reset",
      "gentle-reentry-after-time-away",
      "stressful-week-reset",
    ],
    content: [
      {
        id: "transition-note-1",
        kind: "micro-guide",
        title: "Keep transitions lighter",
        body: "Routines can shift during travel or difficult weeks. A softer restart can still count as continuity.",
      },
    ],
  },
  {
    id: "setback-recovery-support",
    title: "Quiet recovery after setbacks",
    section: "Planning",
    category: "pacing",
    track: "mindfulness",
    premiumFeature: "guided_programs",
    description: "Gentler restart support after difficult weeks, lost routines, or periods when check-ins fell away.",
    whyItHelps: "A quieter return can help after interruptions without turning recovery into pressure.",
    estimatedPace: "1-3 minutes",
    toolIds: ["quiet-restart-after-hard-week", "one-step-reentry", "reduce-discouragement-pressure"],
    content: [
      {
        id: "setback-note-1",
        kind: "micro-guide",
        title: "Keep the restart small",
        body: "A brief return can still matter. Nothing here needs to become a catch-up plan.",
      },
    ],
  },
  {
    id: "future-stability-support",
    title: "Calm future planning",
    section: "Planning",
    category: "pacing",
    track: "mindfulness",
    premiumFeature: "guided_programs",
    description: "Low-pressure support for planning ahead when energy, routines, or the week itself feel less predictable.",
    whyItHelps: "A smaller horizon can help the future feel more workable without turning planning into pressure.",
    estimatedPace: "2-3 minutes",
    toolIds: ["smaller-horizon-planning", "reduce-overcommitment-reset", "gentle-next-week-overview"],
    content: [
      {
        id: "future-note-1",
        kind: "micro-guide",
        title: "Keep the horizon smaller",
        body: "Leaving more room around plans can still count as care, especially when energy is hard to predict.",
      },
    ],
  },
  {
    id: "sleep-support",
    title: "Sleep decompression",
    section: "Rest",
    category: "sleep",
    track: "sleep-support",
    premiumFeature: "guided_programs",
    description: "A calmer evening support set for nights that need less friction and less stimulation.",
    whyItHelps: "A simpler wind-down can make rest feel a little more reachable without turning bedtime into a routine to perform.",
    estimatedPace: "3-5 minutes",
    toolIds: ["sleep-decompression-flow", "quiet-evening-reset"],
    content: [
      {
        id: "sleep-audio-1",
        kind: "audio-cue",
        title: "Optional sound pacing",
        body: "If you like sound, keep it steady and low. Nothing here needs to feel like a performance or meditation session.",
      },
    ],
  },
  {
    id: "bedtime-grounding",
    title: "Bedtime grounding",
    section: "Rest",
    category: "sleep",
    track: "sleep-support",
    premiumFeature: "guided_programs",
    description: "Short support for noisy evenings, mentally crowded nights, and end-of-day decompression.",
    whyItHelps: "The night can feel easier when the day is allowed to quiet down without being fully resolved.",
    estimatedPace: "2-4 minutes",
    toolIds: ["mentally-overloaded-tonight", "bedtime-grounding-prompt"],
    content: [
      {
        id: "bedtime-note-1",
        kind: "reflection-prompt",
        title: "Keep tonight small",
        body: "Nothing here needs to become a perfect routine. A quieter evening can start with one small softening step.",
      },
    ],
  },
  {
    id: "uncertainty-support",
    title: "Uncertainty support",
    section: "Reflection",
    category: "emotional-regulation",
    track: "emotional-resilience",
    premiumFeature: "guided_programs",
    description: "Calmer support for days when uncertainty feels tiring or emotionally noisy.",
    whyItHelps: "A smaller reflection can help without turning the moment into deep processing.",
    estimatedPace: "2 minutes",
    toolIds: ["uncertainty-grounding", "emotional-decompression-flow"],
    content: [
      {
        id: "uncertainty-note-1",
        kind: "reflection-prompt",
        title: "A quieter question",
        body: "What would make this day feel 5% less tense, even if nothing feels fully settled yet?",
      },
    ],
  },
  {
    id: "communication-support",
    title: "Communication support",
    section: "Reflection",
    category: "emotional-regulation",
    track: "emotional-resilience",
    premiumFeature: "guided_programs",
    description: "Practical support for difficult conversations, low-energy communication, and feeling misunderstood.",
    whyItHelps: "A simpler way of explaining today can reduce pressure without turning the moment into a bigger conversation than you have energy for.",
    estimatedPace: "1-3 minutes",
    toolIds: ["short-ways-to-say-low-energy", "explaining-brain-fog-gently", "gentle-boundary-check"],
    content: [
      {
        id: "communication-note-1",
        kind: "micro-guide",
        title: "Keep it short if needed",
        body: "You do not need a perfect explanation. One clear sentence can be enough.",
      },
    ],
  },
];

export const PROGRAM_MODULES: ProgramModule[] = [...CORE_PROGRAM_MODULES, ...PREMIUM_PROGRAM_MODULES];

const CORE_PROGRAM_TOOLS: ProgramTool[] = [
  {
    id: "reduce-overwhelm",
    title: "Reduce overwhelm",
    moduleId: "reduce-overwhelm-support",
    section: "Calm",
    category: "overwhelm",
    whenToUse: "Use this when thoughts, stress, or tasks start piling up.",
    durationLabel: "2 minutes",
    description: "A guided reset for unloading mental pressure and choosing one manageable next step.",
    steps: [
      "Choose the main source of overload.",
      "Name what needs attention today.",
      "Move one thing later, slower, or smaller.",
      "Choose one next step.",
    ],
    completionMessage: "The overload is organized into one next step.",
    futureTrack: "stress-support",
    continuationLabel: "Use this when the day starts feeling crowded.",
    supportTags: ["stress", "overwhelm", "brain-fog"],
  },
  {
    id: "brain-fog-basics",
    title: "Brain fog support",
    moduleId: "brain-fog-basics",
    section: "Planning",
    category: "brain-fog",
    whenToUse: "Use this when focusing, remembering, decisions, or starting tasks feels harder.",
    durationLabel: "2 minutes",
    description: "A cognitive simplification tool for clearing mental clutter and choosing one manageable next step.",
    steps: [
      "Choose what feels hardest right now.",
      "Name one thing that needs attention next.",
      "Make it smaller.",
      "Choose one adjustment that reduces mental load.",
    ],
    completionMessage: "The next step is simpler and easier to start.",
    futureTrack: "cognitive-support",
    continuationLabel: "Use this when too many steps are competing at once.",
    supportTags: ["brain-fog", "planning", "fatigue"],
  },
  {
    id: "appointment-prep",
    title: "Appointment prep",
    moduleId: "appointment-prep-support",
    section: "Planning",
    category: "care-prep",
    whenToUse: "Use this before a care visit to organize symptoms, changes, questions, and medication notes.",
    durationLabel: "5 minutes",
    description: "A practical appointment summary you can share, print, or bring to a provider.",
    steps: [
      "List what changed since your last appointment.",
      "Choose the symptoms that matter most right now.",
      "Write questions or discussion topics.",
      "Add medication or supplement changes.",
      "Name what has been most difficult lately.",
    ],
    completionMessage: "Your appointment summary is ready.",
    futureTrack: "cognitive-support",
    continuationLabel: "Use this before appointments or care conversations.",
    supportTags: ["planning", "brain-fog", "reflection"],
  },
  {
    id: "breathing-reset",
    title: "60-second breathing reset",
    moduleId: "nervous-system-reset",
    section: "Calm",
    category: "grounding",
    whenToUse: "Use this when stress, racing thoughts, or overstimulation are building.",
    durationLabel: "1 minute",
    durationSeconds: 60,
    description: "A 4-2-6 breathing reset for slowing activation and reducing cognitive overload.",
    steps: [
      "Inhale for 4 seconds.",
      "Hold for 2 seconds.",
      "Exhale for 6 seconds.",
      "Repeat until the 60-second reset completes.",
    ],
    completionMessage: "Reset complete.",
    futureTrack: "nervous-system",
    continuationLabel: "Come back to this when the day feels noisy.",
    supportTags: ["stress", "sleep", "overwhelm"],
  },
  {
    id: "body-scan",
    title: "2-minute body scan",
    moduleId: "nervous-system-reset",
    section: "Calm",
    category: "grounding",
    whenToUse: "When you need to check in without pushing yourself.",
    durationLabel: "2 minutes",
    durationSeconds: 120,
    description: "A gentle scan to notice tension, effort, and what your body may need.",
    steps: [
      "Notice your jaw, shoulders, hands, and stomach one by one.",
      "Ask: what feels tight, tired, or tender right now?",
      "See if one part of your body can soften even 5%.",
      "End by choosing the gentlest next step for the next hour.",
    ],
    completionMessage: "You can return to this anytime.",
    futureTrack: "nervous-system",
    continuationLabel: "A body scan can help before choosing what to do next.",
    supportTags: ["stress", "sleep", "fatigue"],
  },
  {
    id: "low-energy-checklist",
    title: "Low-energy day checklist",
    moduleId: "energy-support",
    section: "Energy",
    category: "low-energy",
    whenToUse: "When fatigue is high and the day needs to feel smaller.",
    durationLabel: "2 minutes",
    description: "A quick reminder of what may help on heavier days.",
    steps: [
      "Pick only one priority for today.",
      "Move one non-urgent task out of the way.",
      "Keep water, snacks, and anything supportive nearby.",
      "Choose rest before you fully crash, not after.",
    ],
    completionMessage: "That can be enough for today if you need.",
    futureTrack: "energy-management",
    continuationLabel: "Come back when your energy needs a gentler plan.",
    supportTags: ["fatigue", "planning"],
  },
  {
    id: "one-priority-planner",
    title: "One-priority planner",
    moduleId: "gentle-planning",
    section: "Planning",
    category: "pacing",
    whenToUse: "When everything feels important and you need a clearer next step.",
    durationLabel: "2 minutes",
    description: "A small planning reset to make the day feel more manageable.",
    steps: [
      "Name the one thing that matters most today.",
      "Choose one thing that can wait.",
      "Choose one support action that makes the priority easier.",
      "Give yourself permission to stop once the main thing is done.",
    ],
    completionMessage: "A smaller plan can still be enough.",
    futureTrack: "mindfulness",
    continuationLabel: "This can help when the day feels crowded.",
    supportTags: ["planning", "stress", "brain-fog"],
  },
  {
    id: "hard-moment-reflection",
    title: "Hard moment reflection",
    moduleId: "heavier-day-reflection",
    section: "Reflection",
    category: "emotional-regulation",
    whenToUse: "When you want to process the day without overthinking it.",
    durationLabel: "3 minutes",
    description: "A short reflection to make a hard moment feel a little easier to hold.",
    steps: [
      "What felt hardest today?",
      "What helped, even a little?",
      "What can stay unfinished for now?",
      "What might make tomorrow a little easier?",
    ],
    completionMessage: "You can return to this anytime.",
    futureTrack: "emotional-resilience",
    continuationLabel: "You can return to this after a hard day or week.",
    supportTags: ["reflection", "stress"],
  },
];

const PREMIUM_PROGRAM_TOOLS: ProgramTool[] = [
  {
    id: "symptom-reflection",
    title: "Symptom reflection",
    moduleId: "symptom-reflection-support",
    section: "Reflection",
    category: "brain-fog",
    premiumFeature: "guided_programs",
    whenToUse: "When a symptom change needs clearer context without turning into a long log.",
    durationLabel: "3 minutes",
    description: "A guided pattern-awareness tool for spotting changes, possible triggers, and helpful supports.",
    steps: [
      "Choose the symptom that stands out most.",
      "Mark whether it changed recently.",
      "Select possible triggers.",
      "Select what seems to help.",
      "Choose whether to save it for later discussion.",
    ],
    completionMessage: "The symptom pattern note is ready.",
    futureTrack: "cognitive-support",
    continuationLabel: "Use this when a symptom needs clearer context.",
    supportTags: ["reflection", "brain-fog", "planning"],
  },
  {
    id: "sixty-second-quiet-reset",
    title: "60-second quiet reset",
    moduleId: "overwhelm-support",
    section: "Calm",
    category: "overwhelm",
    premiumFeature: "guided_programs",
    whenToUse: "When everything feels sharp and you need the next minute to feel smaller.",
    durationLabel: "1 minute",
    durationSeconds: 60,
    description: "A very short reset for reducing input before the day asks anything else from you.",
    steps: [
      "Let one source of input soften if you can.",
      "Relax your jaw or shoulders a little.",
      "Choose one slower breath in and one slower breath out.",
      "Let the next minute stay simple.",
    ],
    completionMessage: "A quieter minute may be enough right now.",
    futureTrack: "stress-support",
    continuationLabel: "Return here when the day needs to soften quickly.",
    supportTags: ["stress", "overwhelm"],
  },
  {
    id: "mentally-overloaded-reset",
    title: "Mentally overloaded reset",
    moduleId: "overwhelm-support",
    section: "Calm",
    category: "overwhelm",
    premiumFeature: "guided_programs",
    whenToUse: "When everything feels too loud or too full at once.",
    durationLabel: "2 minutes",
    durationSeconds: 120,
    description: "A shorter reset for moments when you need less input and less pressure.",
    steps: [
      "Stop adding new inputs for one minute if you can.",
      "Pick one surface to look at and let the rest blur out a little.",
      "Say quietly: I only need the next small step.",
      "Choose one simple action or one simple pause.",
    ],
    completionMessage: "You do not need to sort everything out right now.",
    futureTrack: "stress-support",
    continuationLabel: "Return here when the day feels mentally crowded.",
    supportTags: ["stress", "overwhelm", "brain-fog"],
  },
  {
    id: "two-minute-overwhelm-reset",
    title: "2-minute overwhelm reset",
    moduleId: "overwhelm-support",
    section: "Calm",
    category: "overwhelm",
    premiumFeature: "guided_programs",
    whenToUse: "When stress feels sharp and you need the day to soften a little.",
    durationLabel: "2 minutes",
    durationSeconds: 120,
    description: "A brief sequence for slowing the pace without trying to fix everything at once.",
    steps: [
      "Unclench one part of your body.",
      "Lower one expectation for the next hour.",
      "Choose one thing that can wait.",
      "Let the next step stay small.",
    ],
    completionMessage: "A smaller pace may be enough for now.",
    futureTrack: "stress-support",
    continuationLabel: "This can still help if the day stays full later on.",
    supportTags: ["stress", "overwhelm"],
  },
  {
    id: "calming-sensory-reset",
    title: "Calming sensory reset",
    moduleId: "sensory-reset",
    section: "Calm",
    category: "grounding",
    premiumFeature: "guided_programs",
    whenToUse: "When light, sound, movement, or crowded spaces feel like too much.",
    durationLabel: "2 minutes",
    description: "A quieter sensory reset that reduces input before asking anything else from you.",
    steps: [
      "Soften one source of input around you if you can.",
      "Rest your eyes on something visually quieter.",
      "Let your breathing settle without trying to control it too much.",
      "Stay with the calmer setup for one more minute if that helps.",
    ],
    completionMessage: "A quieter setup can be enough for now.",
    futureTrack: "nervous-system",
    continuationLabel: "Return if your surroundings start to feel sharp again.",
    supportTags: ["stress", "overwhelm", "sleep"],
  },
  {
    id: "slow-things-down-reset",
    title: "Slow things down",
    moduleId: "emotional-reset-rituals",
    section: "Calm",
    category: "overwhelm",
    premiumFeature: "guided_programs",
    whenToUse: "When everything feels too loud and you need the next few minutes to ask less from you.",
    durationLabel: "1 minute",
    durationSeconds: 60,
    description: "A short downshift for reducing urgency before the moment spills into the next one.",
    steps: [
      "Let one task or thought move out of the center for a minute.",
      "Unclench one part of your body if you can.",
      "Choose one slower breath in and one slower breath out.",
      "Keep the next minute quieter than the last one.",
    ],
    completionMessage: "A slower minute may be enough right now.",
    futureTrack: "stress-support",
    continuationLabel: "Return here when the moment still feels louder than it needs to.",
    supportTags: ["stress", "overwhelm"],
  },
  {
    id: "nervous-system-downshift",
    title: "Nervous-system downshift",
    moduleId: "emotional-reset-rituals",
    section: "Calm",
    category: "grounding",
    premiumFeature: "guided_programs",
    whenToUse: "When your body still feels activated after a stressful moment or overstimulating stretch.",
    durationLabel: "2 minutes",
    durationSeconds: 120,
    description: "A brief sequence for helping your system settle without needing to process everything first.",
    steps: [
      "Let your eyes rest on one quieter surface.",
      "Soften your shoulders or jaw a little.",
      "Take one slower exhale than feels natural.",
      "Give the next few minutes less input if you can.",
    ],
    completionMessage: "Your system may need a little time to slow down.",
    futureTrack: "nervous-system",
    continuationLabel: "Return here when the body still feels revved up afterward.",
    supportTags: ["stress", "overwhelm", "sleep"],
  },
  {
    id: "reduce-stimulation-guide",
    title: "Reduce stimulation guide",
    moduleId: "sensory-reset",
    section: "Calm",
    category: "grounding",
    premiumFeature: "guided_programs",
    whenToUse: "When sound, light, decisions, or movement feel like too much at once.",
    durationLabel: "1 minute",
    description: "A short guide for making the space around you a little quieter without turning it into a whole routine.",
    steps: [
      "Lower one source of brightness, sound, or movement.",
      "Put one non-urgent input out of reach for now.",
      "Let one surface stay visually simple.",
      "Keep the setup quieter for the next few minutes if that helps.",
    ],
    completionMessage: "A lower-stimulation setup may be enough for now.",
    futureTrack: "nervous-system",
    continuationLabel: "Return when the space around you starts to feel too busy.",
    supportTags: ["stress", "overwhelm", "brain-fog"],
  },
  {
    id: "reduce-emotional-carryover",
    title: "Reduce emotional carryover",
    moduleId: "emotional-reset-rituals",
    section: "Calm",
    category: "overwhelm",
    premiumFeature: "guided_programs",
    whenToUse: "When a stressful moment keeps following you into the next hour.",
    durationLabel: "2 minutes",
    durationSeconds: 120,
    description: "A short reset for leaving a little more space between what just happened and what comes next.",
    steps: [
      "Name what just happened in one plain sentence.",
      "Choose one part of it you do not need to keep replaying right now.",
      "Lower one expectation for the next hour.",
      "Let the next part of the day begin smaller.",
    ],
    completionMessage: "You may not need to carry all of this forward right now.",
    futureTrack: "stress-support",
    continuationLabel: "Return here when the last difficult moment still feels too present.",
    supportTags: ["stress", "overwhelm", "reflection"],
  },
  {
    id: "difficult-morning-support",
    title: "Difficult morning support",
    moduleId: "low-energy-recovery",
    section: "Energy",
    category: "low-energy",
    premiumFeature: "guided_programs",
    whenToUse: "When the morning starts heavy and the day already feels demanding.",
    durationLabel: "3 minutes",
    description: "A smaller morning structure for days that need a gentler start.",
    steps: [
      "Choose the gentlest possible first task.",
      "Put one comfort or support item nearby.",
      "Let the second decision wait until the first one is done.",
      "Keep the next hour quieter if you can.",
    ],
    completionMessage: "A slower start can still count as moving through the day.",
    futureTrack: "energy-management",
    continuationLabel: "This can still help later if the day keeps feeling heavy.",
    supportTags: ["fatigue", "planning", "brain-fog"],
  },
  {
    id: "low-energy-evening-wind-down",
    title: "Low-energy evening wind-down",
    moduleId: "low-energy-recovery",
    section: "Energy",
    category: "low-energy",
    premiumFeature: "guided_programs",
    whenToUse: "When the day has taken a lot and you need an easier evening.",
    durationLabel: "4 minutes",
    description: "A quiet end-of-day sequence that reduces decision load instead of adding another routine.",
    steps: [
      "Choose one or two evening tasks that matter most.",
      "Let one unfinished thing stay unfinished.",
      "Put tomorrow's first support item where you can find it easily.",
      "Make the next hour a little softer if you can.",
    ],
    completionMessage: "An easier evening may be enough tonight.",
    futureTrack: "energy-management",
    continuationLabel: "Return when the evening needs to stay lighter.",
    supportTags: ["fatigue", "sleep", "planning"],
  },
  {
    id: "everything-feels-too-hard",
    title: "Difficult day reset",
    moduleId: "difficult-day-support",
    section: "Energy",
    category: "low-energy",
    premiumFeature: "guided_programs",
    whenToUse: "When the day feels overloaded and expectations need to become smaller.",
    durationLabel: "3 minutes",
    description: "A stabilization tool for reducing pressure, protecting energy, and choosing what is enough today.",
    steps: [
      "Choose what feels hardest right now.",
      "Name one thing that needs attention today.",
      "Make one demand smaller, slower, or later.",
      "Choose one adjustment for the next few hours.",
      "Define what counts as enough today.",
    ],
    completionMessage: "The day has a smaller, more realistic shape.",
    futureTrack: "energy-management",
    continuationLabel: "Use this when a difficult day needs less pressure and clearer expectations.",
    supportTags: ["fatigue", "stress", "overwhelm"],
  },
  {
    id: "i-cant-do-much-today",
    title: "I can’t do much today",
    moduleId: "difficult-day-support",
    section: "Energy",
    category: "low-energy",
    premiumFeature: "guided_programs",
    whenToUse: "When energy is very low and even basic things feel harder to start.",
    durationLabel: "2 minutes",
    description: "A low-capacity checklist for letting the day stay practical instead of pressuring yourself to do more.",
    steps: [
      "Pick one thing that truly matters today.",
      "Choose one thing that can stay unfinished.",
      "Make one support easier to reach.",
      "Stop before you are fully spent if you can.",
    ],
    completionMessage: "A lower-capacity day can still be a real day.",
    futureTrack: "energy-management",
    continuationLabel: "This will still be here if the day stays heavy later on.",
    supportTags: ["fatigue", "planning"],
  },
  {
    id: "less-pressure-reset",
    title: "I need less pressure",
    moduleId: "difficult-day-support",
    section: "Energy",
    category: "low-energy",
    premiumFeature: "guided_programs",
    whenToUse: "When the main thing you need is for the day to stop feeling so demanding.",
    durationLabel: "2 minutes",
    description: "A short support flow for lowering expectations and keeping the rest of the day gentler.",
    steps: [
      "Lower one expectation for the next few hours.",
      "Let one decision wait.",
      "Choose the simpler version of one task.",
      "Keep the rest of the day lighter where you can.",
    ],
    completionMessage: "Reducing pressure may be enough right now.",
    futureTrack: "energy-management",
    continuationLabel: "Return when the day starts asking too much again.",
    supportTags: ["stress", "planning", "fatigue"],
  },
  {
    id: "my-brain-feels-overloaded",
    title: "My brain feels overloaded",
    moduleId: "difficult-day-support",
    section: "Energy",
    category: "low-energy",
    premiumFeature: "guided_programs",
    whenToUse: "When you are exhausted and mentally overloaded at the same time.",
    durationLabel: "2 minutes",
    description: "A small reset for reducing mental effort before the day asks for anything else.",
    steps: [
      "Move one thought out of your head and onto paper.",
      "Choose one thing that does not need attention yet.",
      "Keep only the next step visible.",
      "Let the rest stay quiet for now.",
    ],
    completionMessage: "A quieter mind may be enough for this moment.",
    futureTrack: "cognitive-support",
    continuationLabel: "Return when everything feels mentally crowded again.",
    supportTags: ["brain-fog", "fatigue", "stress"],
  },
  {
    id: "i-need-things-quieter",
    title: "I need things quieter",
    moduleId: "difficult-day-support",
    section: "Energy",
    category: "low-energy",
    premiumFeature: "guided_programs",
    whenToUse: "When the day feels sharp, noisy, or too full and you need less input.",
    durationLabel: "1 minute",
    description: "A simple lowering-stimulation reset for reducing the feeling that everything is too much at once.",
    steps: [
      "Soften one source of input if you can.",
      "Turn away from one thing that can wait.",
      "Take one slower breath without trying to fix the whole moment.",
      "Let the next few minutes stay quieter.",
    ],
    completionMessage: "A quieter setup may be enough right now.",
    futureTrack: "nervous-system",
    continuationLabel: "Return here when the day feels too loud again.",
    supportTags: ["overwhelm", "stress", "fatigue"],
  },
  {
    id: "brain-fog-clarifier",
    title: "Brain fog clarifier",
    moduleId: "brain-fog-support",
    section: "Planning",
    category: "brain-fog",
    premiumFeature: "guided_programs",
    whenToUse: "When thinking feels cloudy and holding onto steps takes more effort.",
    durationLabel: "2 minutes",
    description: "A simpler way to reduce decisions when your mind already feels full.",
    steps: [
      "List the next one or two steps only.",
      "Circle the first one.",
      "Move everything else out of view for now.",
      "Do the first step before choosing another one.",
    ],
    completionMessage: "A smaller mental load may be enough for now.",
    futureTrack: "cognitive-support",
    continuationLabel: "Return when the next few steps feel slippery.",
    supportTags: ["brain-fog", "planning", "fatigue"],
  },
  {
    id: "decision-light-reset",
    title: "Decision-light reset",
    moduleId: "brain-fog-support",
    section: "Planning",
    category: "brain-fog",
    premiumFeature: "guided_programs",
    whenToUse: "When too many choices are making the day feel harder to hold onto.",
    durationLabel: "2 minutes",
    description: "A quick reset for lowering decision load instead of forcing more clarity.",
    steps: [
      "Pick one default for the next block of time.",
      "Delay one non-urgent choice.",
      "Choose the simpler version of one task.",
      "Let the next decision wait until it needs to be real.",
    ],
    completionMessage: "Fewer decisions may help more right now.",
    futureTrack: "cognitive-support",
    continuationLabel: "This can help when the day starts to branch in too many directions.",
    supportTags: ["brain-fog", "planning", "stress"],
  },
  {
    id: "empty-tank-support",
    title: "My brain feels empty",
    moduleId: "mental-exhaustion-recovery",
    section: "Energy",
    category: "brain-fog",
    premiumFeature: "guided_programs",
    whenToUse: "When you feel mentally emptied out and do not have much left for decisions, effort, or pushing through.",
    durationLabel: "2 minutes",
    durationSeconds: 120,
    description: "A low-demand recovery tool for moments when the mind feels spent rather than simply busy.",
    steps: [
      "Let one thing stay undone for now.",
      "Reduce one source of mental input if you can.",
      "Choose one support action that asks almost nothing from you.",
      "Let the next stretch stay smaller than usual.",
    ],
    completionMessage: "A lower-capacity mind may need less pressure, not more.",
    futureTrack: "cognitive-support",
    continuationLabel: "Return here when your brain feels emptied out again.",
    supportTags: ["brain-fog", "fatigue", "stress"],
  },
  {
    id: "mental-rest-permission",
    title: "Mental rest permission",
    moduleId: "mental-exhaustion-recovery",
    section: "Energy",
    category: "low-energy",
    premiumFeature: "guided_programs",
    whenToUse: "When your mind feels depleted and you keep feeling pressure to recover quickly or become productive again.",
    durationLabel: "1 minute",
    durationSeconds: 60,
    description: "A short reset for lowering internal urgency when your brain needs less, not more.",
    steps: [
      "Name one thing your mind does not need to solve right now.",
      "Let one expectation drop for the next hour.",
      "Choose the quieter version of the next task if possible.",
      "Allow mental rest to count for this moment.",
    ],
    completionMessage: "You may not need to mentally recover all at once.",
    futureTrack: "energy-management",
    continuationLabel: "Return when mental rest keeps feeling hard to allow.",
    supportTags: ["fatigue", "stress", "planning"],
  },
  {
    id: "travel-day-pacing",
    title: "Travel day pacing",
    moduleId: "life-transition-support",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "When travel or being away from routine is taking more energy than usual.",
    durationLabel: "2 minutes",
    description: "A smaller pacing reset for days when logistics, movement, or unfamiliar settings are already a lot.",
    steps: [
      "Let the day have fewer expectations if you can.",
      "Keep one comfort or support item easy to reach.",
      "Choose the quieter version of one plan.",
      "Let the next block of time stay simple.",
    ],
    completionMessage: "Travel days may need a gentler pace.",
    futureTrack: "mindfulness",
    continuationLabel: "Return when travel or being away from routine starts to feel louder than expected.",
    supportTags: ["fatigue", "stress", "planning"],
  },
  {
    id: "disrupted-routine-reset",
    title: "Disrupted routine reset",
    moduleId: "life-transition-support",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "When routines have shifted and the week no longer feels predictable.",
    durationLabel: "2 minutes",
    description: "A short reset for days when structure has loosened and you need a softer next step instead of a full reset plan.",
    steps: [
      "Pick one anchor for today, even if it stays small.",
      "Let one unfinished part of the week remain unfinished.",
      "Choose the simplest next block of time you can.",
      "Treat the restart gently instead of trying to catch up.",
    ],
    completionMessage: "A softer restart can be enough.",
    futureTrack: "mindfulness",
    continuationLabel: "This is still here when a disrupted week needs a calmer next step.",
    supportTags: ["planning", "stress", "fatigue"],
  },
  {
    id: "gentle-reentry-after-time-away",
    title: "Gentle re-entry after time away",
    moduleId: "life-transition-support",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "When you are returning after a gap, a hard week, or time away from routine.",
    durationLabel: "1 minute",
    durationSeconds: 60,
    description: "A brief return flow that keeps continuity low-pressure instead of turning it into catching up.",
    steps: [
      "Start with one small re-entry point.",
      "Leave the rest of the gap unexplained for now.",
      "Keep today's version simpler than usual if needed.",
      "Let coming back stay quiet.",
    ],
    completionMessage: "Coming back quietly can still be enough.",
    futureTrack: "mindfulness",
    continuationLabel: "Return here when a restart needs to stay gentle.",
    supportTags: ["planning", "fatigue"],
  },
  {
    id: "stressful-week-reset",
    title: "Stressful week reset",
    moduleId: "life-transition-support",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "When too many changes, logistics, or hard days have landed close together.",
    durationLabel: "3 minutes",
    description: "A steadier reset for weeks when everything changed faster than your energy could keep up.",
    steps: [
      "Name one thing this week does not need from you right now.",
      "Choose one calmer anchor for the next day or two.",
      "Reduce one source of extra stimulation or decision load.",
      "Let the next stretch stay lighter while things settle.",
    ],
    completionMessage: "A steadier next stretch may be enough for now.",
    futureTrack: "mindfulness",
    continuationLabel: "This can still help when a stressful week keeps spilling forward.",
    supportTags: ["stress", "planning", "overwhelm"],
  },
  {
    id: "quiet-restart-after-hard-week",
    title: "Quiet restart after a hard week",
    moduleId: "setback-recovery-support",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "When a difficult week changed your rhythm and even opening the app again feels like a lot.",
    durationLabel: "2 minutes",
    description: "A softer restart that keeps the next step small instead of asking you to recover everything at once.",
    steps: [
      "Let the gap stay a gap without trying to explain all of it.",
      "Pick one small return point for today.",
      "Ignore anything that makes the restart feel bigger than it needs to be.",
      "Let this be enough for now.",
    ],
    completionMessage: "A quiet restart can still be enough.",
    futureTrack: "mindfulness",
    continuationLabel: "Return when restarting needs less pressure.",
    supportTags: ["planning", "fatigue", "stress"],
  },
  {
    id: "one-step-reentry",
    title: "One-step re-entry",
    moduleId: "setback-recovery-support",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "When you want to come back after an interruption but everything feels too big to restart fully.",
    durationLabel: "1 minute",
    durationSeconds: 60,
    description: "A small re-entry cue for lowering the size of the return.",
    steps: [
      "Choose one single thing that would make today a little easier.",
      "Let every other piece of the restart wait.",
      "Keep the next step visible and the rest out of view.",
      "Stop there if that is enough.",
    ],
    completionMessage: "One step can be enough for now.",
    futureTrack: "mindfulness",
    continuationLabel: "This is still here when the return needs to stay very small.",
    supportTags: ["planning", "fatigue"],
  },
  {
    id: "reduce-discouragement-pressure",
    title: "Reduce discouragement pressure",
    moduleId: "setback-recovery-support",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "When discouragement, guilt, or self-pressure is making it harder to begin again.",
    durationLabel: "2 minutes",
    description: "A lower-pressure reset for days when the hardest part is how much the interruption is already weighing on you.",
    steps: [
      "Name one harsh expectation you can lower today.",
      "Let the return be smaller than the pressure says it should be.",
      "Choose one practical next step instead of a full plan.",
      "Keep the rest quiet for now.",
    ],
    completionMessage: "Beginning again without pressure can be enough.",
    futureTrack: "mindfulness",
    continuationLabel: "Return here when discouragement starts making the restart feel heavier.",
    supportTags: ["stress", "planning", "fatigue"],
  },
  {
    id: "smaller-horizon-planning",
    title: "Smaller-horizon planning",
    moduleId: "future-stability-support",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "When planning too far ahead starts to feel heavier than helpful.",
    durationLabel: "2 minutes",
    description: "A shorter-horizon planning reset for keeping the next stretch more workable and less crowded.",
    steps: [
      "Choose the smallest future window that still feels useful.",
      "Let one later decision stay undecided for now.",
      "Keep one area of the week flexible on purpose.",
      "Protect a little room around what matters most.",
    ],
    completionMessage: "A smaller planning horizon may be enough for now.",
    futureTrack: "mindfulness",
    continuationLabel: "Return when planning starts reaching further than your energy can follow.",
    supportTags: ["planning", "stress", "fatigue"],
  },
  {
    id: "reduce-overcommitment-reset",
    title: "Reduce overcommitment reset",
    moduleId: "future-stability-support",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "When too many plans or obligations are stacking up ahead of you.",
    durationLabel: "2 minutes",
    description: "A quick reset for leaving more room around plans before the week starts feeling too full.",
    steps: [
      "Name one plan that can stay smaller.",
      "Let one commitment remain tentative a little longer.",
      "Leave one rest pocket protected if you can.",
      "Choose flexibility over finishing the whole schedule.",
    ],
    completionMessage: "Leaving more room may be enough right now.",
    futureTrack: "mindfulness",
    continuationLabel: "This is still here when the future starts to feel too crowded.",
    supportTags: ["planning", "stress"],
  },
  {
    id: "gentle-next-week-overview",
    title: "Gentle next-week overview",
    moduleId: "future-stability-support",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "When you want a small future view without turning the next week into a big project.",
    durationLabel: "3 minutes",
    description: "A simple next-week overview that keeps planning light, flexible, and energy-aware.",
    steps: [
      "Pick one thing that may matter next week.",
      "Leave one part of the week intentionally open.",
      "Notice one period that may need less demand.",
      "Let the rest stay unfinished for now.",
    ],
    completionMessage: "A lighter next-week view can still be enough.",
    futureTrack: "mindfulness",
    continuationLabel: "Return when the next week needs a softer outline instead of a full plan.",
    supportTags: ["planning", "fatigue", "stress"],
  },
  {
    id: "cognitive-decompression-reset",
    title: "Cognitive overload support",
    moduleId: "brain-fog-support",
    section: "Planning",
    category: "brain-fog",
    premiumFeature: "guided_programs",
    whenToUse: "When tasks, decisions, stimulation, or symptoms are competing for too much attention.",
    durationLabel: "3 minutes",
    description: "A cognitive load-reduction tool for choosing one focus, lowering mental noise, and making demands smaller.",
    steps: [
      "Choose the current overload level.",
      "Name the main source of overload.",
      "Choose one thing that needs attention first.",
      "Make one demand smaller, slower, later, shared, or ignored for today.",
      "Identify the biggest source of mental noise.",
    ],
    completionMessage: "The next step is clearer and the load is smaller.",
    futureTrack: "cognitive-support",
    continuationLabel: "Use this when too many things are competing for attention.",
    supportTags: ["brain-fog", "stress", "planning"],
  },
  {
    id: "slower-recovery-pacing",
    title: "Slower recovery pacing",
    moduleId: "mental-exhaustion-recovery",
    section: "Energy",
    category: "low-energy",
    premiumFeature: "guided_programs",
    whenToUse: "When you feel pressure to bounce back mentally faster than your system actually can.",
    durationLabel: "2 minutes",
    durationSeconds: 120,
    description: "A quiet pacing reset for letting cognitive and emotional recovery happen more slowly.",
    steps: [
      "Choose one thing that can wait until your mind feels less spent.",
      "Keep the next decision smaller than usual.",
      "Lower one expectation around productivity or clarity.",
      "Let the next hour be about less input, not more output.",
    ],
    completionMessage: "Slower recovery can still be real recovery.",
    futureTrack: "energy-management",
    continuationLabel: "Return here when recovery starts feeling rushed or pressured.",
    supportTags: ["fatigue", "stress", "brain-fog"],
  },
  {
    id: "too-many-thoughts-at-once",
    title: "Too many thoughts at once",
    moduleId: "brain-fog-support",
    section: "Planning",
    category: "brain-fog",
    premiumFeature: "guided_programs",
    whenToUse: "When too many thoughts are active and you cannot hold onto one clear next step.",
    durationLabel: "1 minute",
    durationSeconds: 60,
    description: "A quick reset for narrowing the field when everything feels mentally noisy.",
    steps: [
      "Name the one thing that needs your attention first.",
      "Move every other thought onto paper or leave it for later.",
      "Keep only the first step visible.",
      "Let the rest wait until this step is done.",
    ],
    completionMessage: "One clearer next step may be enough.",
    futureTrack: "cognitive-support",
    continuationLabel: "Return when everything starts competing at once.",
    supportTags: ["brain-fog", "planning", "stress"],
  },
  {
    id: "one-thing-at-a-time",
    title: "One thing at a time",
    moduleId: "cognitive-simplification",
    section: "Planning",
    category: "brain-fog",
    premiumFeature: "guided_programs",
    whenToUse: "When multitasking is making the next hour feel harder to hold together.",
    durationLabel: "2 minutes",
    description: "A smaller structure for letting one task be enough for now.",
    steps: [
      "Pick the one thing that matters most in the next hour.",
      "Set one other task aside on purpose.",
      "Give the main task one simple first step.",
      "Come back to the rest later if you need to.",
    ],
    completionMessage: "One thing at a time may be enough right now.",
    futureTrack: "cognitive-support",
    continuationLabel: "This will still be here when the next hour needs less mental branching.",
    supportTags: ["brain-fog", "planning", "fatigue"],
  },
  {
    id: "simplify-the-next-hour",
    title: "Simplify the next hour",
    moduleId: "cognitive-simplification",
    section: "Planning",
    category: "brain-fog",
    premiumFeature: "guided_programs",
    whenToUse: "When the next hour feels too full and your mind needs less to carry.",
    durationLabel: "2 minutes",
    description: "A lighter reset for reducing mental clutter without turning the hour into a system.",
    steps: [
      "Choose one thing that matters and one thing that can wait.",
      "Remove one decision from the next hour if you can.",
      "Keep one support item close by.",
      "Let the hour stay smaller than usual.",
    ],
    completionMessage: "A simpler hour may be enough.",
    futureTrack: "cognitive-support",
    continuationLabel: "Come back when the next hour needs less mental load.",
    supportTags: ["brain-fog", "planning", "fatigue"],
  },
  {
    id: "reduce-mental-load",
    title: "Reduce mental load",
    moduleId: "cognitive-simplification",
    section: "Planning",
    category: "brain-fog",
    premiumFeature: "guided_programs",
    whenToUse: "When decisions, remembering, and switching between things all feel too expensive.",
    durationLabel: "2 minutes",
    description: "A small decompression flow for lowering mental effort before the day asks for more.",
    steps: [
      "List what you do not want to keep in your head.",
      "Use a default choice where you can.",
      "Leave one decision for later on purpose.",
      "Keep the next step gentler than your usual standard.",
    ],
    completionMessage: "Reducing decisions may help right now.",
    futureTrack: "cognitive-support",
    continuationLabel: "Return when the day starts asking too much from your attention.",
    supportTags: ["brain-fog", "planning", "stress"],
  },
  {
    id: "difficult-day-pacing-checklist",
    title: "Fatigue pacing planner",
    moduleId: "pacing-after-overwhelm",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "Use this when fatigue is high or you need to prevent an energy crash.",
    durationLabel: "4 minutes",
    description: "An energy-management tool for matching demands, drains, and recovery before the day gets overloaded.",
    steps: [
      "Choose today’s energy level.",
      "Select the demands that need energy.",
      "Identify the fastest drains.",
      "Make one demand smaller.",
      "Protect recovery moments.",
    ],
    completionMessage: "Your energy plan is easier to pace.",
    futureTrack: "mindfulness",
    continuationLabel: "Return here when the day needs a gentler shape.",
    supportTags: ["planning", "fatigue", "overwhelm"],
  },
  {
    id: "pacing-after-overwhelm",
    title: "Pacing after overwhelming days",
    moduleId: "pacing-after-overwhelm",
    section: "Planning",
    category: "pacing",
    premiumFeature: "guided_programs",
    whenToUse: "After a day that asked too much and made the next one feel fragile.",
    durationLabel: "3 minutes",
    description: "A pacing reset that makes room for recovery without turning it into another plan to perform.",
    steps: [
      "Lower the demand on the first part of tomorrow.",
      "Carry forward only what still matters.",
      "Protect one pocket of rest or quiet.",
      "Let the day rebuild gradually instead of all at once.",
    ],
    completionMessage: "A gentler pace may be enough after a heavy stretch.",
    futureTrack: "mindfulness",
    continuationLabel: "Return when you need a softer re-entry after harder days.",
    supportTags: ["planning", "stress", "overwhelm"],
  },
  {
    id: "sleep-decompression-flow",
    title: "Sleep recovery support",
    moduleId: "sleep-support",
    section: "Rest",
    category: "sleep",
    premiumFeature: "guided_programs",
    whenToUse: "Use this when stress, stimulation, or symptoms make it hard to wind down.",
    durationLabel: "3 minutes",
    description: "A low-friction wind-down tool for lowering activation and simplifying the evening.",
    steps: [
      "Choose what feels most active.",
      "Select one adjustment that lowers stimulation.",
      "Name one thing to release tonight.",
      "Choose whether a short reset would help first.",
      "Pick a realistic recovery focus.",
    ],
    completionMessage: "The evening has a simpler recovery focus.",
    futureTrack: "sleep-support",
    continuationLabel: "Use this when your body is tired but your mind still feels active.",
    supportTags: ["sleep", "stress", "overwhelm"],
  },
  {
    id: "quiet-evening-reset",
    title: "Quiet evening reset",
    moduleId: "sleep-support",
    section: "Rest",
    category: "sleep",
    premiumFeature: "guided_programs",
    whenToUse: "When the day feels hard to put down at night.",
    durationLabel: "3 minutes",
    description: "A small reset for evenings that need less input rather than more effort.",
    steps: [
      "Notice one thing that can stop for the night.",
      "Make one corner of the space quieter.",
      "Pick one thing that belongs to tomorrow, not tonight.",
      "Let the night begin a little earlier if you can.",
    ],
    completionMessage: "A quieter evening may be enough from here.",
    futureTrack: "sleep-support",
    continuationLabel: "Use this when the day feels reluctant to end.",
    supportTags: ["sleep", "stress"],
  },
  {
    id: "mentally-overloaded-tonight",
    title: "Mentally overloaded tonight",
    moduleId: "bedtime-grounding",
    section: "Rest",
    category: "sleep",
    premiumFeature: "guided_programs",
    whenToUse: "When the day is over but your mind still feels too full to settle.",
    durationLabel: "3 minutes",
    durationSeconds: 180,
    description: "A short nighttime reset for evenings that need less stimulation and less mental carrying.",
    steps: [
      "Let one unfinished thought stay unfinished until tomorrow.",
      "Put one source of input out of reach for the night.",
      "Choose one quieter comfort for the next few minutes.",
      "Let the night begin without solving the whole day.",
    ],
    completionMessage: "Tonight can stay simpler from here.",
    futureTrack: "sleep-support",
    continuationLabel: "Return when the night still feels mentally loud.",
    supportTags: ["sleep", "stress", "overwhelm"],
  },
  {
    id: "bedtime-grounding-prompt",
    title: "Bedtime grounding prompt",
    moduleId: "bedtime-grounding",
    section: "Rest",
    category: "sleep",
    premiumFeature: "guided_programs",
    whenToUse: "When you want one calmer question before letting the night quiet down.",
    durationLabel: "2 minutes",
    description: "A brief evening reflection that lowers pressure instead of creating more to think about.",
    steps: [
      "What pressure could stay unfinished tonight?",
      "What would make tonight feel gentler?",
      "What deserves less mental energy tonight?",
    ],
    completionMessage: "A quieter ending may be enough tonight.",
    futureTrack: "sleep-support",
    continuationLabel: "Come back when the night needs a softer landing.",
    supportTags: ["sleep", "reflection", "stress"],
  },
  {
    id: "uncertainty-grounding",
    title: "Uncertainty grounding",
    moduleId: "uncertainty-support",
    section: "Reflection",
    category: "emotional-regulation",
    premiumFeature: "guided_programs",
    whenToUse: "When uncertainty is taking up too much space in the day.",
    durationLabel: "2 minutes",
    description: "A short grounding reflection for days that feel unsettled without getting pulled into deep analysis.",
    steps: [
      "Name what feels uncertain in a few words.",
      "Name what is steady enough for today.",
      "Choose one thing that does not need to be figured out right now.",
      "Let the rest stay unresolved for a little while longer.",
    ],
    completionMessage: "Not everything needs an answer right now.",
    futureTrack: "emotional-resilience",
    continuationLabel: "Return when uncertainty starts asking too much from the day.",
    supportTags: ["reflection", "stress", "overwhelm"],
  },
  {
    id: "emotional-decompression-flow",
    title: "Emotional decompression flow",
    moduleId: "uncertainty-support",
    section: "Reflection",
    category: "emotional-regulation",
    premiumFeature: "guided_programs",
    whenToUse: "When the day has been emotionally loud and you want a softer landing.",
    durationLabel: "3 minutes",
    description: "A low-pressure decompression flow that helps the day settle without asking for deep processing.",
    steps: [
      "Name one feeling without expanding it too much.",
      "Notice one place your body could soften.",
      "Choose one support for later tonight.",
      "Let the rest stay unfinished for now.",
    ],
    completionMessage: "A quieter landing may be enough for tonight.",
    futureTrack: "emotional-resilience",
    continuationLabel: "This can help after fuller emotional days.",
    supportTags: ["reflection", "stress", "overwhelm"],
  },
  {
    id: "short-ways-to-say-low-energy",
    title: "Short ways to say low energy",
    moduleId: "communication-support",
    section: "Reflection",
    category: "emotional-regulation",
    premiumFeature: "guided_programs",
    whenToUse: "When you want a simple way to explain that today needs a gentler pace.",
    durationLabel: "1 minute",
    description: "A few low-pressure ways to say that your energy is lower without overexplaining.",
    steps: [
      "Try: My energy is a little lower right now.",
      "Try: I may need a quieter pace today.",
      "Try: I may need to keep things simpler today.",
      "Use only the version that feels most natural to you.",
    ],
    completionMessage: "One clear sentence may be enough.",
    futureTrack: "emotional-resilience",
    continuationLabel: "Come back if you need a simpler way to say what today feels like.",
    supportTags: ["reflection", "fatigue", "stress"],
  },
  {
    id: "explaining-brain-fog-gently",
    title: "Explaining brain fog gently",
    moduleId: "communication-support",
    section: "Reflection",
    category: "emotional-regulation",
    premiumFeature: "guided_programs",
    whenToUse: "When thinking feels slower and you want to explain that without a long conversation.",
    durationLabel: "2 minutes",
    description: "A short support tool for describing brain fog simply and without extra pressure.",
    steps: [
      "Try: My thinking feels a little slower today.",
      "Try: I may need simpler steps or a little extra time.",
      "Try: I am following, just more slowly right now.",
      "Keep the explanation as short as you need.",
    ],
    completionMessage: "A simple explanation may be enough.",
    futureTrack: "emotional-resilience",
    continuationLabel: "This will still be here if you need to explain a foggier day again.",
    supportTags: ["brain-fog", "reflection", "stress"],
  },
  {
    id: "gentle-boundary-check",
    title: "Gentle boundary check",
    moduleId: "communication-support",
    section: "Reflection",
    category: "emotional-regulation",
    premiumFeature: "guided_programs",
    whenToUse: "When social plans or requests feel heavier than your energy allows right now.",
    durationLabel: "2 minutes",
    description: "A small support flow for protecting energy without turning it into a big confrontation.",
    steps: [
      "Name what feels like too much right now.",
      "Choose one thing you can soften, shorten, or delay.",
      "Try: I need to keep this a little lighter today.",
      "Let that be enough without extra justification if you want.",
    ],
    completionMessage: "Protecting energy can stay gentle.",
    futureTrack: "emotional-resilience",
    continuationLabel: "Return when you need a lower-pressure way to protect energy.",
    supportTags: ["stress", "reflection", "planning"],
  },
  {
    id: "communicating-overwhelm-simply",
    title: "Communicating overwhelm simply",
    moduleId: "communication-support",
    section: "Reflection",
    category: "emotional-regulation",
    premiumFeature: "guided_programs",
    whenToUse: "When everything feels like too much and you want to say that without a long explanation.",
    durationLabel: "2 minutes",
    description: "A brief tool for simplifying how you communicate overwhelm or social pressure.",
    steps: [
      "Try: I am a little overloaded right now.",
      "Try: I may need to keep this conversation shorter today.",
      "Try: I want to stay connected, just more simply.",
      "Use the version that feels least effortful.",
    ],
    completionMessage: "A simpler explanation may be enough right now.",
    futureTrack: "emotional-resilience",
    continuationLabel: "Return when you need a shorter way to say that things feel like too much.",
    supportTags: ["stress", "overwhelm", "reflection"],
  },
  {
    id: "social-plans-pressure-reducer",
    title: "Reducing pressure around social plans",
    moduleId: "communication-support",
    section: "Reflection",
    category: "emotional-regulation",
    premiumFeature: "guided_programs",
    whenToUse: "When social plans feel heavier than expected and you need a lower-pressure way to respond.",
    durationLabel: "2 minutes",
    description: "A calm support tool for softening expectations around plans without overexplaining.",
    steps: [
      "Notice what part of the plan feels like too much.",
      "Choose whether you need to shorten, postpone, or simplify it.",
      "Try: I may need to keep things lighter than usual today.",
      "Leave the rest simple if that is all you have energy for.",
    ],
    completionMessage: "Simplifying plans may be enough today.",
    futureTrack: "emotional-resilience",
    continuationLabel: "Come back when plans start feeling heavier than your energy allows.",
    supportTags: ["stress", "fatigue", "planning"],
  },
];

export const PROGRAM_TOOLS: ProgramTool[] = [...CORE_PROGRAM_TOOLS, ...PREMIUM_PROGRAM_TOOLS];

if (__DEV__) {
  const seenModuleIds = new Set<string>();
  for (const module of PROGRAM_MODULES) {
    if (seenModuleIds.has(module.id)) {
      console.warn("Duplicate program id:", module.id);
    }
    seenModuleIds.add(module.id);
  }

  const seenToolIds = new Set<string>();
  for (const tool of PROGRAM_TOOLS) {
    if (seenToolIds.has(tool.id)) {
      console.warn("Duplicate program id:", tool.id);
    }
    seenToolIds.add(tool.id);
  }
}

export function getProgramToolById(toolId: string | null | undefined) {
  if (!toolId) {
    return null;
  }

  return PROGRAM_TOOLS.find((tool) => tool.id === toolId) ?? null;
}

export function getProgramModuleById(moduleId: string | null | undefined) {
  if (!moduleId) {
    return null;
  }

  return PROGRAM_MODULES.find((module) => module.id === moduleId) ?? null;
}

export function getProgramToolsByModuleId(moduleId: string) {
  return PROGRAM_TOOLS.filter((tool) => tool.moduleId === moduleId);
}
